server:
   port: 4999
   servlet:
        context-path: /ems
spring:
   mvc:
      view:
          prefix: /
          suffix: .jsp          
   data:
      mongodb:
            database: giridb
            port: 27017
            host: localhost
            
